const FACTOR = 9000;
const MAXIMUM_CODE_LENGTH = 4;
const COUNTDOWN_TIME = 5;
const COOLDOWN_TIME = 3;
const BONUS_FACTOR = 0.2;
const MULTIPLICATION_FACTOR = 100;
const MINIMUM_QUESTIONS = 5;
const HOST_USERNAME = 'Organisateur';

export { BONUS_FACTOR, COOLDOWN_TIME, COUNTDOWN_TIME, FACTOR, HOST_USERNAME, MAXIMUM_CODE_LENGTH, MINIMUM_QUESTIONS, MULTIPLICATION_FACTOR };
