const FACTOR = 9000;
const MAXIMUM_CODE_LENGTH = 4;
const COUNTDOWN_TIME = 5;
const COOLDOWN_TIME = 3;
const BONUS_FACTOR = 0.2;
const MULTIPLICATION_FACTOR = 100;
export { BONUS_FACTOR, FACTOR, MAXIMUM_CODE_LENGTH, COOLDOWN_TIME, COUNTDOWN_TIME, MULTIPLICATION_FACTOR };
