export enum MatchEvents {
    JoinRoom = 'joinRoom',
    CreateRoom = 'createRoom',
    RoomMessage = 'roomMessage',
    StartTimer = 'startTimer',
    StopTimer = 'stopTimer',
    AddPlayer = 'addPlayer',
    ToggleLock = 'toggleLock',
    BanUsername = 'banUsername',
    KickPlayer = 'kickPlayer',
    SendPlayersData = 'sendPlayersData',
    NewMessage = 'newMessage',
    StartMatch = 'startMatch',
    NextQuestion = 'nextQuestion',
    SendMessagesHistory = 'sendMessagesHistory',
    RouteToResultsPage = 'routeToResultsPage',
    HistogramHistory = 'histogramHistory',
    HostQuitMatch = 'hostQuitMatch',
    FetchPlayersData = 'fetchPlayersData',
    FetchOldMessages = 'fetchOldMessages',
    Error = 'error',
}
